/**
 * Bundles the Lune bench (harness + baseline + selected cases) into one self-contained Luau chunk
 * that Roblox Studio can run through `execute_luau`.
 *
 * Why a bundle at all: the harness uses Lune file requires (`require("./status")`,
 * `require("../cases/" .. name)`) which do not exist in Roblox, and this place's script sandbox
 * refuses to let the Assistant thread parent or `require` a ModuleScript at all (see studio/README.md).
 * So every module becomes an entry in an in-chunk registry and `require` becomes a shim.
 *
 * Transformations applied to the harness/baseline/case sources, and nothing else:
 *   1. `--!native` / `--!optimize N` lines are stripped from every module; the bundle carries exactly
 *      one header so a run is entirely native or entirely interpreted.
 *   2. Each module body is wrapped in `function(require)` so `require` resolves relative to the
 *      requiring module's own directory.
 *   3. `require("@lune/process")` resolves to an injected `{ args = {...} }` table.
 *   4. `print` is shadowed by a chunk-local that collects lines instead of writing to the console,
 *      so the runner's table comes back as the call's result.
 * The module sources themselves are copied byte for byte.
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";

export interface BundleOptions {
	/** Absolute path of the luau-bench directory. */
	root: string;
	/** Case names as the runner takes them; "baseline" needs no case file. */
	cases: string[];
	/** argv handed to the runner in place of `process.args`. */
	args: string[];
	/** true emits `--!native` alongside `--!optimize 2`. */
	native: boolean;
}

/** Modules every run needs, whatever the case list is. */
const CORE_MODULES = [
	"harness/status",
	"harness/scenarios",
	"harness/baseline_adapter",
	"harness/runner",
	"baseline/BehaviorTree",
	"baseline/Blackboard",
];

const DIRECTIVE = /^[ \t]*--!(native|nonative|optimize[ \t]+\d+)[ \t]*\r?$/gm;

/** A Luau string literal for an arbitrary JS string. */
export function luaStr(s: string): string {
	let out = '"';
	for (const ch of s) {
		const c = ch.codePointAt(0)!;
		if (ch === '"') out += '\\"';
		else if (ch === "\\") out += "\\\\";
		else if (ch === "\n") out += "\\n";
		else if (ch === "\r") out += "\\r";
		else if (c < 0x20 || c === 0x7f) out += "\\" + c;
		else out += ch;
	}
	return out + '"';
}

function stripDirectives(source: string): string {
	// Keep a line in place of each so error line numbers still match the file on disk.
	return source.replace(DIRECTIVE, "-- [bundler: directive moved to the bundle header]");
}

const LITERAL_REQUIRE = /require\(\s*"(\.\.?\/[^"]+)"\s*\)/g;

/**
 * Resolves a relative require spec against a module path ("cases/x" + "../harness/status" -> "harness/status").
 * A `..` that climbs above the bench root is kept literally ("cases/x" + "../../out/B" -> "../out/B"), so the
 * package build in the repo's out/ can be required; the file is then read relative to the bench root.
 */
function resolveSpec(modulePath: string, spec: string): string {
	const parts = modulePath.split("/").slice(0, -1);
	for (const seg of spec.split("/")) {
		if (seg === "." || seg === "") continue;
		if (seg === "..") {
			if (parts.length > 0 && parts[parts.length - 1] !== "..") parts.pop();
			else parts.push("..");
		} else parts.push(seg);
	}
	return parts.join("/");
}

/**
 * Core modules plus the named cases, plus every module they require through a string-literal relative
 * path (transitively), so a case may depend on e.g. `../compiled/Bt2`.
 */
function moduleList(root: string, cases: string[]): string[] {
	const mods = [...CORE_MODULES];
	for (const name of cases) {
		if (name === "baseline") continue;
		const path = `cases/${name}`;
		if (!mods.includes(path)) mods.push(path);
	}
	for (let i = 0; i < mods.length; i++) {
		const source = readFileSync(join(root, `${mods[i]}.luau`), "utf8");
		for (const match of source.matchAll(LITERAL_REQUIRE)) {
			const dep = resolveSpec(mods[i], match[1]);
			if (!mods.includes(dep)) mods.push(dep);
		}
	}
	return mods;
}

/**
 * The module registry, the require shim and the print collector. Defines `__bench_run(argv)`, which
 * runs the harness runner once for the given argv and returns everything it printed.
 */
export function buildRegistry(opts: BundleOptions): string {
	const p: string[] = [];
	const push = (...lines: string[]) => p.push(...lines);

	push("-- luau-bench Studio bundle (generated by studio/bundle.ts; do not edit by hand)");
	push("local MODULES = {}");
	push("local CACHE = {}");
	push("local LOADING = {}");
	push("");
	push("local OUT = {}");
	push("local __print = print -- the real one, before the shadow below");
	// Shadows the global for every module body below, since they are nested in this chunk.
	push("local function print(...)");
	push('\tlocal n = select("#", ...)');
	push("\tlocal parts = table.create(n)");
	push("\tfor i = 1, n do parts[i] = tostring((select(i, ...))) end");
	push('\tOUT[#OUT + 1] = table.concat(parts, "\\t")');
	push("end");
	push("");
	// "harness" + "./status" -> "harness/status"; "cases" + "../harness/status" -> "harness/status".
	push("local function resolve(dir, spec)");
	push('\tif spec:sub(1, 1) == "@" then return spec end');
	push("\tlocal segments = {}");
	push('\tfor seg in (dir .. "/" .. spec):gmatch("[^/]+") do');
	push('\t\tif seg == "." then');
	push("\t\t\tcontinue");
	push('\t\telseif seg == ".." then');
	push('			if #segments > 0 and segments[#segments] ~= ".." then segments[#segments] = nil else segments[#segments + 1] = ".." end');
	push("\t\telse");
	push("\t\t\tsegments[#segments + 1] = seg");
	push("\t\tend");
	push("\tend");
	push('\treturn table.concat(segments, "/")');
	push("end");
	push("");
	push("local function dirname(path)");
	push('\treturn path:match("^(.*)/[^/]*$") or ""');
	push("end");
	push("");
	push("local load_module");
	push("local function make_require(dir)");
	push("\treturn function(spec)");
	push("\t\treturn load_module(resolve(dir, spec))");
	push("\tend");
	push("end");
	push("");
	push("function load_module(path)");
	push("\tlocal hit = CACHE[path]");
	push("\tif hit ~= nil then return hit end");
	push("\tlocal factory = MODULES[path]");
	push('\tif factory == nil then error("bundle: no module " .. path, 2) end');
	push('\tif LOADING[path] then error("bundle: require cycle at " .. path, 2) end');
	push("\tLOADING[path] = true");
	push("\tlocal value = factory(make_require(dirname(path)))");
	push("\tLOADING[path] = nil");
	push("\tif value == nil then value = true end");
	push("\tCACHE[path] = value");
	push("\treturn value");
	push("end");
	push("");

	for (const path of moduleList(opts.root, opts.cases)) {
		const source = stripDirectives(readFileSync(join(opts.root, `${path}.luau`), "utf8"));
		push(`-- ${"=".repeat(94)}`);
		push(`-- ${path}.luau`);
		push(`-- ${"=".repeat(94)}`);
		push(`MODULES[${luaStr(path)}] = function(require)`);
		push(source.replace(/\r?\n$/, ""));
		push("end");
		push("");
	}

	// The Lune-only module the runner reads its argv from.
	push("-- injected stand-in for Lune's process module");
	push("local ARGS = {}");
	push('MODULES["@lune/process"] = function()');
	push("\treturn { args = ARGS }");
	push("end");
	push("");
	push("-- Runs harness/runner.luau once with the given argv and returns everything it printed.");
	push("local function __bench_run(argv)");
	push("\tARGS = argv");
	push("\ttable.clear(OUT)");
	push('\tCACHE["harness/runner"] = nil -- the runner does its work at require time');
	push('\tload_module("harness/runner")');
	push('\treturn table.concat(OUT, "\\n")');
	push("end");
	push("");
	return p.join("\n");
}

/** The sqrt loop from SPEC.md: ~2 ns/iter natively, ~8-20 ns interpreted. */
export function canarySource(indent: string): string {
	return [
		`${indent}local N = 5000000`,
		`${indent}local s = 0`,
		`${indent}local t0 = os.clock()`,
		`${indent}for i = 1, N do s = s + math.sqrt(i) * 1.5 end`,
		`${indent}local ns = (os.clock() - t0) / N * 1e9`,
	].join("\n");
}

export interface DriverOptions extends BundleOptions {
	/** Folder created under Workspace to carry results between calls. */
	folder: string;
	/** Name of this slice; the driver writes its rows under this key. */
	slice: string;
	/** true also times the native-codegen canary before the runner. */
	canary: boolean;
}

/**
 * The full chunk sent to `execute_luau`: the registry plus a driver that runs the slice in a
 * `task.spawn`ed thread and streams its output into a StringValue, so the call itself returns at once
 * and a slice may take as long as it likes. Poll with `pollChunk`.
 */
export function buildDriverChunk(opts: DriverOptions): string {
	const header = opts.native ? "--!native\n--!optimize 2" : "--!optimize 2";
	const b: string[] = [header, ""];
	const push = (...lines: string[]) => b.push(...lines);

	push(buildRegistry(opts));
	push(`-- ${"=".repeat(94)}`);
	push("-- driver");
	push(`-- ${"=".repeat(94)}`);
	push(`local folder = workspace:FindFirstChild(${luaStr(opts.folder)})`);
	push("if folder == nil then");
	push('\tfolder = Instance.new("Folder")');
	push(`\tfolder.Name = ${luaStr(opts.folder)}`);
	push("\tfolder.Archivable = false -- never becomes part of a saved place");
	push("\tfolder.Parent = workspace");
	push("end");
	push(`local slot = folder:FindFirstChild(${luaStr(opts.slice)})`);
	push("if slot == nil then");
	push('\tslot = Instance.new("StringValue")');
	push(`\tslot.Name = ${luaStr(opts.slice)}`);
	push("\tslot.Archivable = false");
	push("\tslot.Parent = folder");
	push("end");
	push('slot.Value = ""');
	push("");
	push("local function emit(line)");
	push('\tslot.Value ..= line .. "\\n"');
	push("end");
	push("");
	push("task.spawn(function()");
	push("\tlocal ok, err = pcall(function()");
	push('\t\temit("#studio\\t" .. version())');
	push(`\t\temit("#mode\\t" .. ${luaStr(opts.native ? "native" : "interp")})`);
	if (opts.canary) {
		push(canarySource("\t\t"));
		push('\t\temit(string.format("#canary\\t%.3f\\t%.0f", ns, s))');
		push("\t\ttask.wait()");
	}
	push("\t\tlocal t0 = os.clock()");
	push(`\t\tlocal text = __bench_run({ ${opts.args.map(luaStr).join(", ")} })`);
	push("\t\temit(text)");
	push('\t\temit(string.format("#seconds\\t%.2f", os.clock() - t0))');
	push("\tend)");
	push('\tif not ok then emit("#error\\t" .. tostring(err)) end');
	push('\temit("#DONE")');
	push("end)");
	push("");
	push(`return "started " .. ${luaStr(opts.slice)}`);
	return b.join("\n");
}

/** Reads one slice's accumulated output. */
export function pollChunk(folder: string, slice: string): string {
	return [
		`local f = workspace:FindFirstChild(${luaStr(folder)})`,
		'if f == nil then return "#MISSING" end',
		`local s = f:FindFirstChild(${luaStr(slice)})`,
		'if s == nil then return "#MISSING" end',
		"return s.Value",
	].join("\n");
}

/** Removes everything the driver put in the place. */
export function cleanupChunk(folder: string): string {
	return [
		`local f = workspace:FindFirstChild(${luaStr(folder)})`,
		'if f == nil then return "nothing to clean" end',
		"f:Destroy()",
		`return "removed workspace." .. ${luaStr(folder)}`,
	].join("\n");
}
